### ISSUE TITLE
動かん

### ISSUE THREAD

**Issue by Yutarotaro** [astaka-pe/posterization#3]
Traceback (most recent call last):
  File "/Users/yutaro/2023/others/posterization/main_gui.py", line 8, in <module>
    import cv2
  File "/opt/homebrew/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/opt/homebrew/lib/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/cv2/python-3.11/cv2.cpython-311-darwin.so, 0x0002): Library not loaded: '/opt/homebrew/opt/openexr/lib/libOpenEXR-3_1.30.dylib'
  Referenced from: '/opt/homebrew/Cellar/opencv/4.7.0_4/lib/libopencv_imgcodecs.4.7.0.dylib'
  Reason: tried: '/opt/homebrew/opt/openexr/lib/libOpenEXR-3_1.30.dylib' (no such file), '/usr/local/lib/libOpenEXR-3_1.30.dylib' (no such file), '/usr/lib/libOpenEXR-3_1.30.dylib' (no such file), '/opt/homebrew/Cellar/openexr/3.2.1/lib/libOpenEXR-3_1.30.dylib' (no such file), '/usr/local/lib/libOpenEXR-3_1.30.dylib' (no such file), '/usr/lib/libOpenEXR-3_1.30.dylib' (no such file)

**Comment by astaka-pe** [comment]
@Yutarotaro Good luck!

**Comment by Yutarotaro** [comment]
草
きつすぎるなー
